# Generated by Django 5.2.5 on 2025-08-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('roblox_user_id', models.CharField(max_length=255)),
                ('roblox_user_name', models.CharField(max_length=255)),
                ('race_start', models.DateTimeField()),
                ('race_time', models.FloatField()),
                ('collisions', models.JSONField(blank=True, default=list)),
                ('tracking', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
