# Generated by Django 5.2.5 on 2025-08-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestchunk',
            name='race_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
