# Generated by Django 5.2.5 on 2025-08-11 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('studies', models.ManyToManyField(blank=True, related_name='researchers', to='research_admin.study')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('group', models.CharField(choices=[('control', 'Control'), ('experimental', 'Experimental')], max_length=20)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='research_admin.study')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('preset_id', models.IntegerField()),
                ('level_id', models.IntegerField(blank=True, null=True)),
                ('phase_id', models.IntegerField(blank=True, null=True)),
                ('intervention_id', models.IntegerField(blank=True, null=True)),
                ('moment_id', models.IntegerField()),
                ('result_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('date', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_used', models.BooleanField(default=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='research_admin.participant')),
            ],
            options={
                'indexes': [models.Index(fields=['participant', 'date'], name='research_ad_partici_c2fe39_idx'), models.Index(fields=['is_active', 'is_used'], name='research_ad_is_acti_598a72_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['study', 'email'], name='research_ad_study_i_8c27ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('study', 'email'), name='uniq_participant_email_per_study'),
        ),
    ]
