# Generated by Django 5.2.5 on 2025-08-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='match',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='match',
            name='moment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
