# Generated by Django 5.2.5 on 2025-08-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_admin', '0002_remove_match_created_at_remove_match_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='screen_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
