# Generated by Django 5.2.5 on 2025-08-22 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_admin', '0003_match_screen_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('destroy_time', models.DateTimeField(blank=True, null=True)),
                ('launch_time', models.DateTimeField(blank=True, null=True)),
                ('hit_time', models.DateTimeField(blank=True, null=True)),
                ('mature_time', models.DateTimeField(blank=True, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('launch_coord_x', models.FloatField(blank=True, null=True)),
                ('launch_coord_y', models.FloatField(blank=True, null=True)),
                ('hit_coord_x', models.FloatField(blank=True, null=True)),
                ('hit_coord_y', models.FloatField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='research_admin.match')),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'launch_time'], name='research_ad_match_i_7498ec_idx')],
            },
        ),
    ]
